[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "16.16.0"
  NPM_VERSION = "8.11.0"

[context.production]
  command = "npm run build"

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false
